name: smart_personal_finance_app
description: A new Flutter project for personal finance management.

# Prevents accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

  # Data storage
  shared_preferences: ^2.5.3

  # Charts (compatible with Dart 3.6.0)
  syncfusion_flutter_charts: ^29.1.38

  # ✅ Circular percent indicator for savings chart
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
